#define SIZE_ICON 25
#define SIZE_GROUP_CIRCLE 30

#define COLOR_HOVER_WP [1,1,1,0.6]
#define COLOR_CONTRAST [1,1,1,1]

#define COLOR_SELECTED_GROUP [0.9,0.9,0,0.75]
#define COLOR_CONTRAST_GROUP [1,1,1,0.75]

// Vehicles
#define COLOR_VEHICLE [0.5,0.5,0.5,0.75]
#define COLOR_CONTRAST_VEHICLE [1,1,1,0.75]

// General icons
#define ICON_CIRCLE_FILL "\a3\Ui_F_Curator\Data\CfgCurator\entity_selected_ca.paa"
#define ICON_CIRCLE_BORDER "\a3\Ui_F_Curator\Data\CfgCurator\entity_ca.paa"

// Base icons
#define ICON_BASE "\A3\ui_f\data\map\markers\nato\u_installation.paa"
#define ICON_BASE_FILL "\a3\Ui_f\data\GUI\Rsc\RscDisplayMultiplayerSetup\flag_civil_ca.paa"
#define ICON_BASE_OUTLINE "\a3\Ui_f\data\GUI\Rsc\RscDisplayMultiplayerSetup\flag_civil_empty_ca.paa"
#define COLOR_BASE_CONTRAST [1,1,1,0.5]


// waypoints
#define ICON_WAYPOINT "\A3\ui_f\data\map\groupicons\waypoint.paa"

// Selection Box
#define COLOR_SELECTION_BOX [0.85,0.4,0,1]


// Icon text size
#define SIZE_TEXT_CALLSIGN 0.045